### ISSUE TITLE
Scoria Stone is generating (very often) in the overworld

### ISSUE THREAD

**Issue by SpencerMeow** [AOCAWOL/BYG-1#11]
This is on the latest Forge version on 1.16.5

I don't even half to walk a few blocks underground before encountering scoria stone, which I thought made no sense to have underground but I looked in the config and its only supposed to be in the nether and end, but for some reason it is generating in the overworld, this possibly may be happening with soap stone too.

**Comment by AOCAWOL** [comment]
So ! = not so in the config what you are reading is the exact opposite :) Scoria & Soapstone only spawn in the overworld I am closing this as Scoria is actually in our next update being located to 1 specific nether biome so it will no longer be relevant.
