### ISSUE TITLE
BYG not working in the End or Nether with Terraforged

### ISSUE THREAD

**Issue by cheshyrp** [AOCAWOL/BYG-1#14]
I'm not certain that Terraforged is responsible, as I'm unwilling to scrap my world to test. However, using NBT explorer on the created world confirms that the generator for The End and The Nether were set to their default Minecraft valutes; not BYG's as expected.

**Comment by Junibluebee** [comment]
You have to change the generator settings in Terraforged, its not Biomes you'll go's fault. On the first page in terraforged's settings if you scroll down you will see a generation tab thing for the nether, end, and overworld. You have to change it to biomes you'll go's generation settings for the nether and end and then it will generate the biomes.

**Comment by Junibluebee** [comment]
> I'm not certain that Terraforged is responsible, as I'm unwilling to scrap my world to test. However, using NBT explorer on the created world confirms that the generator for The End and The Nether were set to their default Minecraft valutes; not BYG's as expected.

You have to change the generator settings in Terraforged, its not Biomes you'll go's fault. On the first page in terraforged's settings if you scroll down you will see a generation tab thing for the nether, end, and overworld. You have to change it to biomes you'll go's generation settings for the nether and end and then it will generate the biomes.

**Comment by cheshyrp** [comment]
Thank you, Juibluebee. I generated the world in server mode, so never saw a settings page. As you probably know, when you run a server it just immediately creates a world without any prompts. Anyway it's fixed now. Yeah!
