### ISSUE TITLE
Missing Kasai Texture

### ISSUE THREAD

**Issue by NaofaArach** [AOCAWOL/BYG-1#19]
**Modloader:** Forge 14.23.5.2855 - 1.12.2

**Other Mods Installed:** 1st Run - BOP / 2nd Run None

**What did you Expect to happen:** The Kasai ore to generate with texture.

**What happened Instead:** Kasai Ore is missing texture and is showing the normal Missing texture.

*What have you done to Fix:**
- Delete Config
- Reinstall Forge
- Reinstall Mods
- Solo install
- Delete config

**Other notes:** The only thing I can thing to try is go back to previous versions. I understand that you are working on 1.17, Just wondering what else I could do. Working on a mod pack and it spawns so much its noticeable.
![2021-08-14_21 52 32](https://user-images.githubusercontent.com/67977842/129464480-4574921f-6b7a-47d2-be27-03259e627f7e.png)
![2021-08-14_21 52 47](https://user-images.githubusercontent.com/67977842/129464482-3506de81-1f46-4de9-b881-43bb3a7f7d7b.png)

**Comment by AOCAWOL** [comment]
Sorry but 1.12 is an unsupported legacy version.
