### ISSUE TITLE
BYG's Nether biomes are not compatible with BOP

### ISSUE THREAD

**Issue by C1ffisme** [AOCAWOL/BYG-1#39]
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

Yes. This is entirely an issue surrounding mod conflicts with Biomes O' Plenty (and possibly any other mods that add biomes to the Nether or End)

__**API/Modloader**__

Forge. BOP does not work on Fabric.

__**Describe the bug**__

Due to faults in how Nether Biomes work described in [this](https://github.com/Glitchfiend/BiomesOPlenty/issues/1755) issue on the BOP Github, BYG biomes will not spawn in a world with the Biomes O' Plenty world type. The issue is best summarized by a comment from BOP developer Forstride:

> This isn't necessarily a fault with either mod, but there's not really a good way to handle this, as the Nether doesn't really have a proper biome list or anything by default like the Overworld does. It has some weird noise values for each biome or whatever, so we had to create our own system for our Nether biomes, which requires an override of the Nether dimension's biome provider.

> I don't know how BYG handles their Nether biomes, but unless Forge implements some uniform way to handle Nether biomes, we're probably not going to do anything about support for other mods. As for the End, it's probably another situation where they have their own End provider, but since we have our world type, it's set to use vanilla's End provider.

Seeing that BOP does not intend to implement mod support at this time, it would seem that unfortunately the last resort then is to have mod developers adding Nether biomes support BOP. I've put this as a "major" issue since I would consider an inability to make use of both mods' Nether features without going down some sort of desperate route like stringing together a datapack that combines the biomes of both mods to be a very hacky and undesirable solution for modpack authors and the like.

Theoretically, the same issue could apply to End biomes, but I do not think the latest BOP adds any End biomes.

**Comment by CorgiTaco** [comment]
BYG works with Biomes O'Plenty(BOP) for the most part. Currently BYG sub biomes do NOT work in their worldtype.

To enable BYG's Nether Biomes in their worldtype, set use_bop_nether to false in their config.

**Comment by C1ffisme** [comment]
> BYG works with Biomes O'Plenty(BOP) for the most part. Currently BYG sub biomes do NOT work in their worldtype.
> 
> To enable BYG's Nether Biomes in their worldtype, set use_bop_nether to false in their config.

This is still not exactly "compatibility". At the very least it would be nice if BYG still spawned BOP Nether biomes if the two mods are installed.

**Comment by CorgiTaco** [comment]
it does! just delete our nether biome config and let it regenerate and itll have bop biomes

**Comment by C1ffisme** [comment]
Just tested it and I can confirm you are right, I'm sorry to have wasted your time though I'm glad I could get the issue resolved. Thank you!

**Comment by CorgiTaco** [comment]
Lowk my fault for not having a faq
