### ISSUE TITLE
Crash when entering nether when using Terra world gen and BYG

### ISSUE THREAD

**Issue by AlexMcFacepalm** [AOCAWOL/BYG-1#4]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
Crash when entering the nether.

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
Yes with the Terra world generator.

__**API/Modloader**__
Forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Game crashes when entering the nether when the world generator chosen is TERRA:Default.

__**To Reproduce**__
Please provide step by step instructions
Choose Terra:default on world gen settings. Build nether portal. Enter.

**Expected behavior**
To be able to enter the nether with a combined world gen of Terra with the biomes of BYG

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
This link has both latest and crash log: https://paste.ee/p/CAdzH

**Comment by CorgiTaco** [comment]
This is to be reported to them not BYG

**Comment by AlexMcFacepalm** [comment]
Writing one to them too.
