### ISSUE TITLE
Meadow Grass Path is slow to mine with a Shovel

### ISSUE THREAD

**Issue by NillerMedDild** [AOCAWOL/BYG-1#5]
__**API/Modloader**__
Forge

__**Describe the bug**__
Meadow Grass Path is very slow to mine with a Shovel.

__**To Reproduce**__
Mine Meadow Grass Path with any Shovel. I used an Iron Shovel.

**Expected behavior**
For the Shovel to be effective at mining the Meadow Grass Path, like with normal path.

**Additional context**
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2409

**Comment by YaBoiChips** [comment]
fixed
