### ISSUE TITLE
Tall flowers from BYG do not compost in a vanilla composter

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [AOCAWOL/BYG-1#6]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__
Unsure, need to test alone. 

__**API/Modloader**__
Forge

__**Describe the bug**__
Clearing out some flowers in an allium fields and composting my flowers, and the tall ones do not compost. 

__**To Reproduce**__
Collect tall allium flowers.
Create composter.
Right click composter with tall flower. 
No flowers added. 
Note: Regular size flowers work.

**Expected behavior**
I expected tall allium flowers to compost like their short sized ones. 

**Screenshots/Videos**
![Screen Shot 2021-06-27 at 6 17 46 PM](https://user-images.githubusercontent.com/16616656/123566230-07161d00-d774-11eb-9ed3-105b69053a80.png)

**Additional context**
ATM6, latest version of modpack
forge 31.1.31
BYG 1.2.9

**Logs**
No logs to provide.

**Comment by AOCAWOL** [comment]
-Fixed will be in our upcoming update :)
