### ISSUE TITLE
World is corrupted (server) 

### ISSUE THREAD

**Issue by Ymjoe** [AOCAWOL/BYG-1#7]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
It doesn't work by itself (on my server)

__**API/Modloader**__
Fabric

__**Describe the bug**__
I have a minecraft server, and i really wanted to add this mod, everything works fine (when booting up the server) But when you join the world, it is super corrupted, a lot of items missing, and people can fly (a slow buggy flight, like when you crawl in cobweb) 

I can see that the biomes are generating, but 80% of stuff is missing, it might be all the custom blocks 

All other mods work, it is just this one 

__**To Reproduce**__
1) Make fabric server 
2) Test without mod
3) Add the mod (i tried the new, and the old version)
4) Join the server
5) BUG

**Expected behavior**

Not sure i understand :((

**Comment by YaBoiChips** [comment]
dont change mods without changing worlds
